#! /bin/bash

# Remove reside mass column generated by 
# GENENMM -res -mass flags in DDPT 

PDB_PATH=$1

# Keep only A conformation
sed -i 's/\(^ATOM.\{63\}\)....\..../\1        /g' ${PDB_PATH}
sed -i 's/\(^HETATM.\{61\}\)....\..../\1        /g' ${PDB_PATH}

